### ISSUE TITLE
Implement a sort function for ArrayList<Task>

### ISSUE THREAD

**Issue by mxchai** [cs2103jan2015-w15-1j/main#74]
To be used after every CRUD operation.

**Comment by Muhammad-Adam** [comment]
Done. Take note that the sort method only sort incompleted task. Please reopen the issue if there is a need to sort completed tasks. Thanks.

**Comment by Muhammad-Adam** [comment]
Sorry. Didnt read properly. Will redo

**Comment by sebastianquek** [comment]
The sorting order is as follows:
1. Floating
2. Overdue
3. Task sorted by date (nearest to latest), tasks with times are after non-timed ones.

E.g.
1. Read Fifty Shades of Grey
2. Finish cs2105 assignment 2 on 22 March 2015
3. Watch Liverpool vs Man U match on 22 March from 9:30pm to 11pm
4. Do Tutorial 10 for cs2105 on 28 March 2015
5. Watch Malaysian GP qualifying on 28 March 2015 from 5pm to 6pm

(task 1 is floating, task 2 and 3 are overdue, task 4 and 5 are upcoming, notice that the timed tasks are shown after deadline tasks)

**Comment by Muhammad-Adam** [comment]
Ok. Have done it as requested. Note that it wont be sorted in chronological order in the same category though.

**Comment by sebastianquek** [comment]
Please get it working, with the tasks sorted in chronological order. Tasks that occur on the same day should be grouped together. As in the example, 2 is a deadline task and 3 is a timed-task and they appear next to each other since they are on the same day.

We need this for the display, tasks should be displayed in chronological order like in our mockups.

**Comment by Muhammad-Adam** [comment]
Ok. Done as requested.
